### PR TITLE
Fix unused step defs

### PR DESCRIPTION
**Pull request by UL-ChrisGlew**
### 🤔 What's changed?

The 'Find Unused Step Definitions' context menu should no longer show step definitions decorated with the 'StepDefinition' attribute as unused when one or more is used with a Given/Then/When.

### ⚡️ What's your motivation? 

Fix for #22. 

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

I've attempted to add a new unit test to test this. This involved adding some logic to correctly add a 'StepDefinition' attribute into the 'MockableDiscoveryService' - let me know if there's any better way of doing this.

### 📋 Checklist:

- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.

----

*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Review by gasparnagy — CHANGES_REQUESTED** [review]
This is cool! The code is fine.

My only request is to update the changelog. (Besides adding a line about the change, please also add a line at the end of the section starting with `*Contributors of this release (in alphabetical order):* `, and put your own GitHub handle there, similarly how we just started with the core project here: https://github.com/reqnroll/Reqnroll/blob/main/CHANGELOG.md?plain=1

**Comment by UL-ChrisGlew** [comment]
@gasparnagy I've updated the Changelog with the requested changes.

**Review by gasparnagy — APPROVED** [review]
Thx!

**Comment by gasparnagy** [comment]
@UL-ChrisGlew I added you to the group already, but you still deserve the "official" intro: 😎 Thx for the help!

Thank you for the contribution! According to our [guidelines](https://github.com/orgs/reqnroll/discussions/67) I have invited you to the Reqnroll [contributors team](https://github.com/orgs/reqnroll/teams/contributors/members). Congrats! 🎉 If you accept it, you will be able to make pull requests easier in the future.

You are also welcome on our discord server: https://go.reqnroll.net/discord-invite

**Pull request merged**
