### PR TITLE
Adding missing assemblies.

### LINKED ISSUE #37: Reqnroll Extension v2024.3.152 does not work on Visual Studio 17.11.4
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Content of reqnroll.json (if present)

_No response_

### Issue Description

When attempting to load a Reqnroll project on the latest version of Visual Studio 2022 with the latest Reqnroll extension installed, the extension will not load and functionality is not present. 

### Steps to Reproduce

1. Have a Reqnroll solution
2. Install latest Visual Studio 2022 updates
3. Install latest Reqnroll extension (v2024.3.152)
4. Extension functionality is not present.

image

### Workaround

**We have issued a hotfix, to the simplest workaround is to update the package to v2024.4.154 that should work.**

An alternative workaround for this issue would be to downgrade the Visual Studio 2022 extension to the previous version.

The download for the previous version can be found here:

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Reqnroll/vsextensions/ReqnrollForVisualStudio2022/2024.2.93/vspackage

To downgrade, you'll need to

- Uninstall the current Reqnroll for Visual Studio 2022 extension
- Disable automatic updates (for now):
image
- Then close Visual Studio 2022 and install the VSIX file downloaded in the URL above.

### PR DESCRIPTION
**Pull request by UL-ChrisGlew**
### 🤔 What's changed?

Adding missing dependency files:
- TestableIO.System.IO.Abstractions.dll
- TestableIO.System.IO.Abstractions.Wrappers.dll

That are now required due to an update in the System.IO.Abstractions package. I have tested this on an envrionment where #37 could be replicated. Tested both the broken VSIX file and one created with the lines ammended, which seems to function correctly.

### ⚡️ What's your motivation? 

To fix #37 

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

N/A

### 📋 Checklist:

- [*] Users should know about my change
  - [*] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.

----

*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Review by gasparnagy — APPROVED** [review]
Fantastic. Thx for the quick analysis and fix. You are the hero of the day! 🤘

**Comment by gasparnagy** [comment]
@UL-ChrisGlew When you played with it locally, have you observed any issues with the `Diagnostics.LoggingTests` class from the unit test suite? We have a flaky error there, see #40.

**Comment by UL-ChrisGlew** [comment]
I hadn't initially - have re-run the unit tests a few times and had one test fail in that time due to #40 - so does seem to be a flaky error.

**Comment by UL-ChrisGlew** [comment]
I've just run them again and set to run until failure, and have not had any logging tests fail in 78 iterations - the failure that I have got was not related to logging:
image

**Comment by gasparnagy** [comment]
Hm... that is something else. From the "Specs" project there might be such errors sometimes - not good, but that are integration tests. But the worrying about the logger tests that they are unit tests, and (at least on the CI) more often happen. Just to double check: When you used "run until failure" have you done that for the `Reqnroll.VisualStudio.Tests` project?

One more: Could you please try to upgrade the `ApprovalTests` dependency to 6.0.0 and see if the flakiness comes for the logger tests?

**Comment by UL-ChrisGlew** [comment]
Yes, I've been running the whole `Reqnroll.VisualStudio.Tests` as 'Run until failure' and am not seeing any failures around those logging tests at the moment. I left just those logging tests running for ~500 iterations and they've not yet failed.

Have just updated the `ApprovalTests` package and ran again, failed after 11 iterations but I don't think it's related?

image

**Comment by gasparnagy** [comment]
I think it's just coincidence, but who knows...

**Comment by gasparnagy** [comment]
This particular error I have seen already a few times already in SpecFlow times...

**Comment by UL-ChrisGlew** [comment]
Ran again and have a different failure:

image

Again, don't think this is related?

**Comment by gasparnagy** [comment]
Hm... Maybe these are also more frequent now. Anyhow. It seems we have quite some flakiness in our tests, so we will need to dig into these one after the other... 

Maybe what happened is that the unit test framework has been improved to run the test parallel slightly differently, and now more of these come up.

**Comment by gasparnagy** [comment]
The question is whether we should wait with releasing the fixed dependencies. Because these seem to be more of testing issues and not related to the product itself.

**Comment by UL-ChrisGlew** [comment]
I don't think it's related to the fixed dependencies - have just checked out the project prior to the package updates going through and am still getting some sporadic failures in the unit tests:

image

**Comment by gasparnagy** [comment]
OK. Could you please copy this last comment to #40 and let's track the flaky problems there.

**Pull request merged**
